version: '3.8'

x-env: &common-env
  NODES: "192.168.137.212:8001,192.168.137.212:8002,192.168.137.212:8003,192.168.137.80:8004,192.168.137.80:8005"
  N: "3"
  W: "2"
  R: "2"

services:
  node1:
    build: .
    container_name: dynamo-node1-1
    environment:
      <<: *common-env
      NODE_ID: "192.168.137.212:8001"
    ports:
      - "8001:8000"

  node2:
    build: .
    container_name: dynamo-node2-1
    environment:
      <<: *common-env
      NODE_ID: "192.168.137.212:8002"
    ports:
      - "8002:8000"

  node3:
    build: .
    container_name: dynamo-node3-1
    environment:
      <<: *common-env
      NODE_ID: "192.168.137.212:8003"
    ports:
      - "8003:8000"
